### ISSUE TITLE
"e is undefined" whenever I try to create a coin

### ISSUE THREAD

**Issue by Tylersuard** [interest-protocol/sui-coins#369]
I filled out the whole form on suicoins, but when I click create, I get the "e is undefined" error:

![image](https://github.com/user-attachments/assets/b5331ae2-d00f-41bb-9363-49c735da721a)

I am following this tutorial:
https://www.youtube.com/watch?v=w6XX8PD7U4U

**Comment by git-marcopitra** [comment]
Hey @Tylersuard, can you provide more context, share the form information, which browser, and which Operating System

**Comment by git-marcopitra** [comment]
I installed Firefox right now, but I cannot find the Sui Wallet (default wallet) on the Extension store, which wallet are you using?

**Comment by Tylersuard** [comment]
I think the Sui Wallet, I just created it on the suicoin website.

**Comment by Tylersuard** [comment]
I tried switching to Chrome, and now it gives me a different error: Cannot read properties of undefined (reading 'map')

**Comment by git-marcopitra** [comment]
I tried here on Firefox with Stashed Wallet, and it worked. Can you try again or change the browser? If It does not work, we'll be here to help you

For private support (to share more details) you can also open a ticket on our Discord: https://discord.com/invite/interestprotocol

**Comment by git-marcopitra** [comment]
> I tried switching to Chrome, and now it gives me a different error: Cannot read properties of undefined (reading 'map')

It's weird, let me double check here

**Comment by Tylersuard** [comment]
I created my suicoin walled using stashed.  I just went to suicoin.com and created my stashed wallet through there.  Then when I tried to create a coin I kept getting all these errors.

**Comment by git-marcopitra** [comment]
@Tylersuard I think I found the issue, can you check if you have SUI on your [wallet](https://getstashed.com)?

**Comment by git-marcopitra** [comment]
By the way, if I am correct we need to improve our error for this case

**Comment by Tylersuard** [comment]
I have no SUI, the wallet is empty, I have not added anything yet.

**Comment by git-marcopitra** [comment]
So, that's why, to execute any transaction on Sui or any other blockchain, you should have gas (the blockchain coin to pay transaction costs). So, to help you I'll send you some SUI, to create a coin and then you tell me if it worked or not.

Claim your SUI by clicking [here](https://www.suicoins.com/send/link#$W8m/DrN5215dBqk4G/97Ou54d7FjB45R0HWFkT2nNRI=)

**Comment by Tylersuard** [comment]
@git-marcopitra Thank you so much!  That worked, I was able to create a coin and send it :)
